---
environment_variables:
  OXIDIZED_VERSION: "0.29.1-1"
git:
  branch: master
clean_workspace: true
builders:
  - docker
docker_name: config/oxidized-custom
docker_tags:
  - "${OXIDIZED_VERSION}"
  - "latest"
docker_no_cache: true
